name: Deploy Infrastructure and Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_infra:
    name: Deploy Infrastructure via Bicep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --template-file infra/azuredeploy.bicep \
            --parameters appName=ebon-app \
                         primaryRegion=australiasoutheast \
                         secondaryRegions='["westeurope","westus"]' \
                         storageAccountType=Standard_LRS \
                         frontDoorSkuName=Standard_AzureFrontDoor \
                         frontDoorEndpointName=${{ secrets.FRONT_DOOR_ENDPOINT_NAME }}

  build_functions:
    name: Build and Package Azure Functions
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore Dependencies
        run: dotnet restore ./functions/FunctionApp.csproj

      - name: Build and Publish Function App
        run: dotnet publish ./functions/FunctionApp.csproj --configuration Release --output ./publish

      - name: Create Zip Package
        run: zip -r functionapp.zip ./publish

      - name: Upload Function App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: functionapp-zip
          path: functionapp.zip

  deploy_functions:
    name: Deploy Azure Functions to Regions
    runs-on: ubuntu-latest
    needs: build_functions
    strategy:
      matrix:
        region: [australiasoutheast, westeurope, westus]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Function App Artifact
        uses: actions/download-artifact@v3
        with:
          name: functionapp-zip
          path: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Function App in ${{ matrix.region }}
        run: |
          FUNCTION_APP_NAME="ebon-app-func-${{ matrix.region }}"
          echo "Deploying to Function App: $FUNCTION_APP_NAME"
          az functionapp deployment source config-zip \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name $FUNCTION_APP_NAME \
            --src functionapp.zip
